from cgi import print_exception


a = 1
print(a)
print(isinstance(a,int))